AllCops:
  Include:
    - 'app.rb'
    - 'controllers/**/*.rb'
    - 'helpers/**/*.rb'
    - 'models/**/*.rb'
  Exclude:
    - 'views/views.rb'
    - 'helpers/**/*.rb'
    - 'i18n'

  DisplayCopNames: true
  StyleGuideCopsOnly: false

Rails:
  Enabled: false

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 15

Style/Documentation:
  Enabled: false

Style/ClassVars:
  Enabled: false
